version: '3.1'
services:
  mysqldb:
    image:  ubuntu/mysql:8.0-21.10_beta
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: My:S3cr3t/
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  hellorestserver:
    image: hellorestserver:localdev
    depends_on:
      - 'mysqldb'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=My:S3cr3t/
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306      